name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: ghcr.io
          name: ghcr.io/Sunnatullox/nest-top-api
          username: ${{ secrets.DOCKER_USERNAME }}  # Ensure this secret is set correctly
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"
